config/routes.rb
Rails.application.routes.draw do
 

  resources :departments
  resources :events
  resources :employee_educations
  resources :employee_bank_details
  resources :employee_contacts
  resources :employees do
  end

  get 'home/index'

  devise_for :users

  root 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	#has_one :employee_bank_detail
	#has_one :employee_contact
	#has_one :employee_education
	#belongs_to :department
	
  #validates :first_name, :last_name,  :technology,  presence: true
  #validates :employee_no, uniqueness: true, length: { maximum: 8 }
  
    include MultiStepModel
	def self.search(search)
	  where("first_name LIKE ?", "%#{search}%") 
	end

  def self.total_steps
    4
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :load_wizard, only: [:new, :edit, :create, :update]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    if params[:search]
      @employees = Employee.search(params[:search])
    else
      @employees = Employee.all
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = @wizard.object
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = @wizard.object
    if @wizard.save
      redirect_to @employee, notice: "Product saved!"
    else
      render :new
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    if @wizard.save
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   byebug  
  #   @employee = Employee.search(params[:name]) if params[:name]
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_no, :first_name, :middle_name, :last_name, :date_of_birth, 
        :marital_status, :father_name, :mother_name, :department, :technology, :joining_date, :address, 
        :current_address, :home_phone, :mobile_no, :alternet_mobile_no, :email, :father_contact_no, :pan_no,
        :national_id_no, :bank_acc_no, :ifsc_code, :bank_name, :branch_address, :exam_passed, :board_or_university, :institut_name, :specialization, :marks)
    end

    def load_wizard
      @wizard = ModelWizard.new(@employee || Employee, session, params)
      if self.action_name.in? %w[new edit]
        @wizard.start
      elsif self.action_name.in? %w[create update]
        @wizard.process
      end
    end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<!-- multistep form -->
<%= form_for @employee,  :html => {:id => "msform"} do |f| %>
  <!-- progressbar -->
  <ul id="progressbar" style="margin-bottom: 16px; margin-top: -23px; width: 608px; margin-left: -120px;">
    <li class="active"></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
  <!-- fieldsets -->
  <fieldset>
    <h2 class="fs-title">Create your account</h2>
    <div id="error_msg" style="color: red;"></div>
    <div class="form-group" >
      <%= f.label :employee_no, :class=>"control-label" %>
      <%= f.text_field :employee_no, :class=>"form-control req" %>
    </div>

    <div class="form-group">
      <%= f.label :first_name, :class=>"control-label" %>
      <%= f.text_field :first_name, :class=>"form-control req" %>
    </div>

    <div class="form-group">
      <%= f.label :middle_name, :class=>"control-label" %>
      <%= f.text_field :middle_name, :class=>"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, :class=>"control-label" %>
      <%= f.text_field :last_name, :class=>"form-control req" %>
    </div>

    <div class="form-group">
      <%= f.label :date_of_birth, :class=>"control-label" %>
      <%= f.date_field :date_of_birth, :class => "form-control req" %>
    </div>

    <div class="form-group">
      <%= f.label :marital_status, :class=>"control-label" %>
      <%= f.select :marital_status, ['Married', 'Single'], {:prompt => 'Select Marital Status'},  { :class => 'form-control req', :style => "width: 100% !important;"}%>
    </div>
    <div class="form-group">
      <%= f.label :father_name, :class=>"control-label " %>
      <%= f.text_field :father_name, :class=>"form-control req" %>
    </div>

    <div class="form-group">
      <%= f.label :mother_name, :class=>"control-label" %>
      <%= f.text_field :mother_name, :class=>"form-control req" %>
    </div>

    <div class="dropdown">
      <%= f.label :department, :class=>"control-label" %>
      <%= f.select :department, ['PHP', 'ROR', 'Design', 'Android', 'Iphon', 'HR'],{:prompt => 'Select Department'}, { :class => 'form-control req', :style => "width: 100%;"} %>
    </div>

    <div class="form-group">
      <%= f.label :technology, :class=>"control-label" %>
      <%= f.select :technology, ['PHP', 'ROR', 'Design', 'Android', 'Iphon'], {:prompt => 'Select Technology'}, { :class => 'form-control req', :style => "width: 100%;"} %>
    </div>
        
    <div class="form-group">
      <%= f.label :joining_date, :class=>"control-label" %>
      <%= f.text_field :joining_date, :class => "form-control req", :placeholder=> "mm/dd/yyyy", "data-provide" => "datepicker" %> 
    </div>
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Social Profiles</h2>
     <div class="form-group" >
    <%= f.label :address %>
    <%= f.text_area :address, :class => "form-control", :style=>"width: 100%;" %>
  </div>
  <div class="form-group">
    <%= f.label :current_address %>
    <%= f.text_area :current_address, :class => "form-control", :style=>"width: 100%;" %>
  </div>
  <div class="form-group">
    <%= f.label :home_phone %>
    <%= f.text_field :home_phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mobile_no %>
    <%= f.text_field :mobile_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :alternet_mobile_no %>
    <%= f.text_field :alternet_mobile_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :father_contact_no %>
    <%= f.text_field :father_contact_no, :class => "form-control" %>
  </div>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Personal Details</h2>
    <div class="form-group">
    <%= f.label :exam_passed %>
    <%= f.text_field :exam_passed, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :board_or_university %>
    <%= f.text_field :board_or_university, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :institut_name %>
    <%= f.text_field :institut_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :specialization %>
    <%= f.text_field :specialization, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :marks %>
    <%= f.text_field :marks, :class => "form-control" %>
  </div>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Personal Details</h2>
    <div class="form-group">
    <%= f.label :pan_no %>
    <%= f.text_field :pan_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :national_id_no %>
    <%= f.text_field :national_id_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bank_acc_no %>
    <%= f.text_field :bank_acc_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ifsc_code %>
    <%= f.text_field :ifsc_code, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bank_name %>
    <%= f.text_field :bank_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :branch_address %>
    <%= f.text_field :branch_address, :class => "form-control" %>
  </div>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" />
  </fieldset>
<% end %>

<!-- jQuery -->
<script src="http://thecodeplayer.com/uploads/js/jquery-1.9.1.min.js" type="text/javascript"></script>

<script src="http://thecodeplayer.com/uploads/js/jquery.easing.min.js" type="text/javascript"></script>
<script type="text/javascript">
//jQuery time
var current_fs, next_fs, previous_fs; //fieldsets
var left, opacity, scale; //fieldset properties which we will animate
var animating; //flag to prevent quick multi-click glitches
var error = 0;
$(".next").click(function(){
  if(animating) return false;
  animating = true;
  
  current_fs = $(this).parent();
  next_fs = $(this).parent().next();
  var fields = $("#msform").find('.req'); 

  fields.each(function() {
    var value = $(this).val();
    if(value == null || value.length <1|| value == 'NULL' ||value==""){
      $(this).addClass('error');
      $("#error_msg").html("Please fill in all of the required fields");
      error++;

      if(error == 1)
      {
        $(this).focus();
      }
    }else{
      $(this).removeClass('error');
      return true;
    }
   
  });
  
  // if(error==0)
  //   return true;
  // else
  //   return true;

  //activate next step on progressbar using the index of next_fs
  $("#progressbar li").eq($("fieldset").index(next_fs)).addClass("active");
  
  //show the next fieldset
  next_fs.show(); 
  //hide the current fieldset with style
  current_fs.animate({opacity: 0}, {
    step: function(now, mx) {
      //as the opacity of current_fs reduces to 0 - stored in "now"
      //1. scale current_fs down to 80%
      scale = 1 - (1 - now) * 0.2;
      //2. bring next_fs from the right(50%)
      left = (now * 50)+"%";
      //3. increase opacity of next_fs to 1 as it moves in
      opacity = 1 - now;
      current_fs.css({'transform': 'scale('+scale+')'});
      next_fs.css({'left': left, 'opacity': opacity});
    }, 
    duration: 800, 
    complete: function(){
      current_fs.hide();
      animating = false;
    }, 
    //this comes from the custom easing plugin
    easing: 'easeInOutBack'
  });
});

$(".previous").click(function(){
  if(animating) return false;
  animating = true;
  
  current_fs = $(this).parent();
  previous_fs = $(this).parent().prev();
  
  //de-activate current step on progressbar
  $("#progressbar li").eq($("fieldset").index(current_fs)).removeClass("active");
  
  //show the previous fieldset
  previous_fs.show(); 
  //hide the current fieldset with style
  current_fs.animate({opacity: 0}, {
    step: function(now, mx) {
      //as the opacity of current_fs reduces to 0 - stored in "now"
      //1. scale previous_fs from 80% to 100%
      scale = 0.8 + (1 - now) * 0.2;
      //2. take current_fs to the right(50%) - from 0%
      left = ((1-now) * 50)+"%";
      //3. increase opacity of previous_fs to 1 as it moves in
      opacity = 1 - now;
      current_fs.css({'left': left});
      previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
    }, 
    duration: 800, 
    complete: function(){
      current_fs.hide();
      animating = false;
    }, 
    //this comes from the custom easing plugin
    easing: 'easeInOutBack'
  });
});


 

</script>

app/views/employees/edit.html.erb
<div id="page-wrapper">

  <div class="row" style="max-width: 60% !important; margin-left: 172px !important;">
    

		<%= render 'form' %>

		<%#= link_to 'Show', @employee %> 
		<%#= link_to 'Back', employees_path %>
	</div>
</div>	

app/views/employees/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <h1>Listing Employees</h1>
    <% if @employees.present? %>
      <div class="table table-striped">
        <table class="table" style="max-width: 60%;">
          <thead>
            <tr class="warning">
              <th>S. NO</th>
              <th>Employee no</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each_with_index do |employee, index| %>
              <tr class="<%= index%2 == 0 ? 'success' : 'danger' %>">
                <td><%= employee.first_name %></td>
                <td><%= employee.employee_no %></td>
                <td><%= link_to 'Show', employee %></td>
                <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
                <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
     <% else %> 
       <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
    <% end %>
    <br>

    <%= link_to 'Back', root_path %>
  </div>
</div>    

app/views/employees/new.html.erb
<div id="page-wrapper">
  
  <div class="row" style="max-width: 60% !important; margin-left: 172px !important;">

		<%= render 'form' %>

		<%#= link_to 'Back', employees_path %>
	</div>
</div>		
	


<script type="text/javascript">
  // $(document).ready(function(){ 
  //   $('.datepicker').datepicker();
  // });
</script>

app/views/employees/show.html.erb
<div id="page-wrapper">
  <div class="row">

    <div class="row">
      <div class="col-lg-12">
      <% if current_user.has_role? :admin %>
        <%= link_to "Edit Info", edit_employee_path(@employee), :class=> "btn btn-primary", :id => "add_employee", :style => "float: right; margin-top: 24px;"%>
      <% end %>
        <h3 class="page-header"><%= @employee.first_name %> <%= @employee.last_name%></h3> 
      </div>
    </div>
      <p id="notice"><%= notice %></p>

      <div class="col-sm-6 col-lg-3">
        <h4 class="emp_font"> <b>Employee Details</b> </h4>
        <p>
          <strong>Employee no:</strong>
          <%= @employee.employee_no %>
        </p>

       
        <p>
          <strong>Middle name:</strong>
          <%= @employee.middle_name %>
        </p>

        <p>
          <strong>Last name:</strong>
          <%= @employee.last_name %>
        </p>

        <p>
          <strong>Date of birth:</strong>
          <%= @employee.date_of_birth %>
        </p>

        <p>
          <strong>Marital status:</strong>
          <%= @employee.marital_status %>
        </p>

        <p>
          <strong>Father name:</strong>
          <%= @employee.father_name %>
        </p>

        <p>
          <strong>Mother name:</strong>
          <%= @employee.mother_name %>
        </p>
        <p>
          <strong>Technology:</strong>
          <%= @employee.technology %>
        </p>

        <p>
          <strong>Date of join:</strong>
          <%= @employee.joining_date %>
        </p>
      </div>


          <div class="col-sm-6 col-lg-3">
            <h4 class="emp_font"> <b>Employee Contact Details</b> </h4>  
          <p>
            <strong>Address:</strong>
            <%= @employee.address %>
          </p>
          <p>
            <strong>Current Address:</strong>
            <%= @employee.current_address %>
          </p>
          <p>
            <strong>Home Phone:</strong>
            <%= @employee.home_phone %>
          </p>
          <p>
            <strong>Mobile Number:</strong>
            <%= @employee.mobile_no %>
          </p>
          <p>
            <strong>Alternet Mobile No:</strong>
            <%= @employee.alternet_mobile_no %>
          </p>
          <p>
            <strong>Email:</strong>
            <%= @employee.email %>
          </p>
          <p>
            <strong>Father Contact No:</strong>
            <%= @employee.father_contact_no %>
          </p>
        </div>
        <div class="col-sm-6 col-lg-3">  
        <h4 class="emp_font"> <b>Education Details</b> </h4>  
          <p>
            <strong>Exam Passed:</strong>
            <%= @employee.exam_passed %>
          </p>
          <p>
            <strong>Board Or University:</strong>
            <%= @employee.board_or_university %>
          </p>
          <p>
            <strong>Institut Name:</strong>
            <%= @employee.institut_name %>
          </p>
          <p>
            <strong>Specialization:</strong>
            <%= @employee.specialization %>
          </p>
          <p>
            <strong>Marks:</strong>
            <%= @employee.marks %>
          </p>
        </div> 
         
        <div class="col-sm-6 col-lg-3">  
        <h4 class="emp_font"> <b>Bank Details</b> </h4> 
          <p>
            <strong>PAN No:</strong>
            <%= @employee.pan_no %>
          </p>
          <p>
            <strong>National Id No:</strong>
            <%= @employee.national_id_no %>
          </p>
          <p>
            <strong>Bank A/C No:</strong>
            <%= @employee.bank_acc_no %>
          </p>
          <p>
            <strong>Ifsc Code:</strong>
            <%= @employee.ifsc_code %>
          </p>
          <p>
            <strong>Bank Name:</strong>
            <%= @employee.bank_name %>
          </p>
           <p>
            <strong>Branch Address:</strong>
            <%= @employee.branch_address %>
          </p>
        <!-- <div class="panel-footer">
          <%#= link_to 'Add Contact',new_employee_contact_path(@employee.id) %>  
          <%#= link_to 'Add Education', new_employee_education_path(@employee.id) %> 
          <%#= link_to 'Add Bank Details', new_employee_bank_detail_path(@employee.id) %>
        </div>   -->
    </div>   
  </div>
</div>