config/routes.rb
Rails.application.routes.draw do
 

  resources :departments
  resources :events
  resources :employee_educations
  resources :employee_bank_details
  resources :employee_contacts
  resources :employees do
  end

  get 'home/index'

  devise_for :users

  root 'home#index'

end

app/models/employee_bank_detail.rb
class EmployeeBankDetail < ActiveRecord::Base
	belongs_to :employee
end

app/controllers/employee_bank_details_controller.rb
class EmployeeBankDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee_bank_detail, only: [:show, :edit, :update, :destroy]

  # GET /employee_bank_details
  # GET /employee_bank_details.json
  def index
    @employee_bank_details = EmployeeBankDetail.all
  end

  # GET /employee_bank_details/1
  # GET /employee_bank_details/1.json
  def show
  end

  # GET /employee_bank_details/new
  def new
    @employee_bank_detail = EmployeeBankDetail.new
    if params[:format]
      @employee = Employee.where("id = ?", params[:format]).first
    end
  end

  # GET /employee_bank_details/1/edit
  def edit
  end

  # POST /employee_bank_details
  # POST /employee_bank_details.json
  def create
    @employee_bank_detail = EmployeeBankDetail.new(employee_bank_detail_params)

    respond_to do |format|
      if @employee_bank_detail.save
        format.html { redirect_to @employee_bank_detail, notice: 'Employee bank detail was successfully created.' }
        format.json { render :show, status: :created, location: @employee_bank_detail }
      else
        format.html { render :new }
        format.json { render json: @employee_bank_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_bank_details/1
  # PATCH/PUT /employee_bank_details/1.json
  def update
    respond_to do |format|
      if @employee_bank_detail.update(employee_bank_detail_params)
        format.html { redirect_to @employee_bank_detail, notice: 'Employee bank detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_bank_detail }
      else
        format.html { render :edit }
        format.json { render json: @employee_bank_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_bank_details/1
  # DELETE /employee_bank_details/1.json
  def destroy
    @employee_bank_detail.destroy
    respond_to do |format|
      format.html { redirect_to employee_bank_details_url, notice: 'Employee bank detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_bank_detail
      @employee_bank_detail = EmployeeBankDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_bank_detail_params
      params.require(:employee_bank_detail).permit(:employee_id, :pan_no, :national_id_no, :bank_acc_no, :ifsc_code, :bank_name, :branch_address)
    end
end

app/helpers/employee_bank_details_helper.rb
module EmployeeBankDetailsHelper
end

app/views/employee_bank_details/_form.html.erb
<%= form_for(@employee_bank_detail) do |f| %>
  <% if @employee_bank_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_bank_detail.errors.count, "error") %> prohibited this employee_bank_detail from being saved:</h2>

      <ul>
      <% @employee_bank_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :employee_id, :value => @employee.id  %>
  
  <div class="form-group">
    <%= f.label :pan_no %><br>
    <%= f.text_field :pan_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :national_id_no %><br>
    <%= f.text_field :national_id_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bank_acc_no %><br>
    <%= f.text_field :bank_acc_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ifsc_code %><br>
    <%= f.text_field :ifsc_code, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bank_name %><br>
    <%= f.text_field :bank_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :branch_address %><br>
    <%= f.text_field :branch_address, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_bank_details/edit.html.erb
<h1>Editing Employee Bank Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_bank_detail %> |
<%= link_to 'Back', employee_bank_details_path %>

app/views/employee_bank_details/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <div class="row">
      <div class="col-lg-12">
      <% if current_user.has_role? :admin %>
        <%#= link_to "Edit Info", edit_employee_path(@employee), :class=> "btn btn-primary", :id => "add_employee", :style => "float: right; margin-top: 24px;"%>
      <% end %>
        <h3 class="page-header">Employee Bank Details</h3> 
      </div>
    </div>

    <table class="table table-striped table-bordered table-hover dataTable no-footer" >
      <thead>
        <tr>
          <th>Emp No</th>
          <th>Name</th>
          <th>Pan no</th>
          <th>National id no</th>
          <th>Bank acc no</th>
          <th>Ifsc code</th>
          <th>Bank name</th>
          <th>Branch address</th>
          
        </tr>
      </thead>

      <tbody>
        <% @employee_bank_details.each do |employee_bank_detail| %>
          <tr>
            <% employee = Employee.where("id =? ", employee_bank_detail.employee_id).first%>
            <td><%= employee.employee_no %></td>
            <td><%= employee.first_name %></td>
            <td><%= employee_bank_detail.pan_no %></td>
            <td><%= employee_bank_detail.national_id_no %></td>
            <td><%= employee_bank_detail.bank_acc_no %></td>
            <td><%= employee_bank_detail.ifsc_code %></td>
            <td><%= employee_bank_detail.bank_name %></td>
            <td><%= employee_bank_detail.branch_address %></td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%#= link_to 'New Employee bank detail', new_employee_bank_detail_path %>
  </div>
</div>  

app/views/employee_bank_details/new.html.erb
<div id="page-wrapper">
  <div class="row" style="max-width: 60% !important; margin-left: 172px !important;">
	<h1> Add <%= @employee.first_name %>'s Bank Details</h1>
	<%= render 'form' %>
	<%= link_to 'Back', employee_bank_details_path %>
	</div>
</div>	

app/views/employee_bank_details/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Employee:</strong>
      <%= @employee_bank_detail.employee_id %>
    </p>

    <p>
      <strong>Pan no:</strong>
      <%= @employee_bank_detail.pan_no %>
    </p>

    <p>
      <strong>National id no:</strong>
      <%= @employee_bank_detail.national_id_no %>
    </p>

    <p>
      <strong>Bank acc no:</strong>
      <%= @employee_bank_detail.bank_acc_no %>
    </p>

    <p>
      <strong>Ifsc code:</strong>
      <%= @employee_bank_detail.ifsc_code %>
    </p>

    <p>
      <strong>Bank name:</strong>
      <%= @employee_bank_detail.bank_name %>
    </p>

    <p>
      <strong>Branch address:</strong>
      <%= @employee_bank_detail.branch_address %>
    </p>

    <%= link_to 'Edit', edit_employee_bank_detail_path(@employee_bank_detail) %> |
    <%= link_to 'Back', employee_bank_details_path %>
  </div>
</div>    