config/routes.rb
Rails.application.routes.draw do
 

  resources :departments
  resources :events
  resources :employee_educations
  resources :employee_bank_details
  resources :employee_contacts
  resources :employees do
  end

  get 'home/index'

  devise_for :users

  root 'home#index'

end

app/models/employee_contact.rb
class EmployeeContact < ActiveRecord::Base
	belongs_to :employee
end

app/controllers/employee_contacts_controller.rb
class EmployeeContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee_contact, only: [:show, :edit, :update, :destroy]

  # GET /employee_contacts
  # GET /employee_contacts.json
  def index
    @employee_contacts = EmployeeContact.all
  end

  # GET /employee_contacts/1
  # GET /employee_contacts/1.json
  def show
  end

  # GET /employee_contacts/new
  def new
    @employee_contact = EmployeeContact.new
    if params[:format]
      @employee = Employee.where("id = ?", params[:format]).first
    end 
  end

  # GET /employee_contacts/1/edit
  def edit
  end 

  # POST /employee_contacts
  # POST /employee_contacts.json
  def create
    @employee_contact = EmployeeContact.new(employee_contact_params)

    respond_to do |format|
      if @employee_contact.save
        
        format.html { redirect_to @employee_contact, notice: 'Employee contact was successfully created.' }
        format.json { render :show, status: :created, location: @employee_contact }
      else
        format.html { render :new }
        format.json { render json: @employee_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_contacts/1
  # PATCH/PUT /employee_contacts/1.json
  def update
    respond_to do |format|
      if @employee_contact.update(employee_contact_params)
        format.html { redirect_to @employee_contact, notice: 'Employee contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_contact }
      else
        format.html { render :edit }
        format.json { render json: @employee_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_contacts/1
  # DELETE /employee_contacts/1.json
  def destroy
    @employee_contact.destroy
    respond_to do |format|
      format.html { redirect_to employee_contacts_url, notice: 'Employee contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_contact
      @employee_contact = EmployeeContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_contact_params
      params.require(:employee_contact).permit(:employee_id, :address, :current_address, :home_phone, :mobile_no, :alternet_mobile_no, :email, :father_contact_no)
    end
end

app/helpers/employee_contacts_helper.rb
module EmployeeContactsHelper
end

app/views/employee_contacts/_form.html.erb
<%= form_for(@employee_contact) do |f| %>
  <% if @employee_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_contact.errors.count, "error") %> prohibited this employee_contact from being saved:</h2>

      <ul>
      <% @employee_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :employee_id, :value => @employee.id  %>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :current_address %>
    <%= f.text_area :current_address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :home_phone %>
    <%= f.text_field :home_phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mobile_no %>
    <%= f.text_field :mobile_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :alternet_mobile_no %>
    <%= f.text_field :alternet_mobile_no, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :father_contact_no %>
    <%= f.text_field :father_contact_no, :class => "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit :class=>"btn btn-primary"  %>
  </div>
<% end %>

app/views/employee_contacts/edit.html.erb
<h1>Editing Employee Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_contact %> |
<%= link_to 'Back', employee_contacts_path %>

app/views/employee_contacts/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <p id="notice"><%= notice %></p>
     <div class="row">
      <div class="col-lg-12">
      <% if current_user.has_role? :admin %>
        <%#= link_to "Edit Info", edit_employee_path(@employee), :class=> "btn btn-primary", :id => "add_employee", :style => "float: right; margin-top: 24px;"%>
      <% end %>
        <h3 class="page-header">Employee Contacts Details</h3> 
      </div>
    </div>
    
    <table class="table table-striped table-bordered table-hover dataTable no-footer">
      <thead>
        <tr>
          <th>Emp No</th>
          <th>Name</th>
          <th>Address</th>
          <th>Current address</th>
          <th>Home phone</th>
          <th>Mobile no</th>
          <th>Alternet mobile no</th>
          <th>Email</th>
          <th>Father contact no</th>
        </tr>
      </thead>

      <tbody>
        <% @employee_contacts.each do |employee_contact| %>
          <tr>
            <% employee = Employee.where("id =? ", employee_contact.employee_id).first%>
            <td><%= employee.employee_no %></td>
            <td><%= employee.first_name %></td>
            <td><%= employee_contact.address %></td>
            <td><%= employee_contact.current_address %></td>
            <td><%= employee_contact.home_phone %></td>
            <td><%= employee_contact.mobile_no %></td>
            <td><%= employee_contact.alternet_mobile_no %></td>
            <td><%= employee_contact.email %></td>
            <td><%= employee_contact.father_contact_no %></td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%#= link_to 'New Employee contact', new_employee_contact_path %>
  </div>
</div>    

app/views/employee_contacts/new.html.erb
<div id="page-wrapper">
  <div class="row">
     <div class="col-lg-12">
       <%#= link_to "Add Employee", new_employee_path, :class=> "btn btn-primary", :id => "add_employee", :style => "float: right; margin-top: 24px;"%>
      <h3 class="page-header">Add <%= @employee.first_name %>'s Contact Details</h3> 
     </div>
  </div>
   <div class="row" style="max-width: 60% !important; margin-left: 172px !important;">
		<%= render 'form' %>
		<%#= link_to 'Back', employee_contacts_path %>
	</div>	
</div>	

app/views/employee_contacts/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Address:</strong>
      <%= @employee_contact.address %>
    </p>

    <p>
      <strong>Current address:</strong>
      <%= @employee_contact.current_address %>
    </p>

    <p>
      <strong>Home phone:</strong>
      <%= @employee_contact.home_phone %>
    </p>

    <p>
      <strong>Mobile no:</strong>
      <%= @employee_contact.mobile_no %>
    </p>

    <p>
      <strong>Alternet mobile no:</strong>
      <%= @employee_contact.alternet_mobile_no %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @employee_contact.email %>
    </p>

    <p>
      <strong>Father contact no:</strong>
      <%= @employee_contact.father_contact_no %>
    </p>

    <%= link_to 'Edit', edit_employee_contact_path(@employee_contact) %> |
    <%= link_to 'Back', employee_contacts_path %>
  </div>
</div>    